services:
  core:
    build:
      dockerfile: ./Dockerfile
    tty: true
    volumes:
      - "${PWD}/src:/opt/src/"
    depends_on:
      - postgres
  postgres:
    image: postgres:11
    restart: unless-stopped
    volumes:
       - "${PWD}/db-data:/var/lib/postgresql/data"
       - "./init_scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql"
    ports:
      - "54322:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      retries: 10
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_NUMBER: 5432
      POSTGRES_DATABASE: postgress 
      POSTGRES_HOSTNAME: localhost 

  postgres_test:
    # Use a set version to secure code from minor changes on the latests image version
    image: postgres:11
    container_name: postgres_test_development
    environment:
      # These variables would ideally be stored in 
      # AWS SecretsManager/other in non-test environments
      POSTGRES_DB: mydatabase  
      POSTGRES_USER: myuser 
      POSTGRES_PASSWORD: mypassword 
      POSTGRES_HOSTNAME: localhost
    ports:
      - "5433:5432" 